alias lf='ls -AF'
alias ll='ls -lAF'
alias wrenv='/c/windriver/wrenv.sh -p vxworks-6.3'
alias ppcmake='wrenv make -C PPC603gnu'
alias deploy='wput -v --reupload --dont-continue --binary PPC603gnu/*/Debug/*.out ftp://10.14.25.2/ni-rt/system/FRC_UserProgram.out'
alias undeploy='wdel -v --binary ftp://10.14.25.2/ni-rt/system/FRC_UserProgram.out'
